version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6 # Use the version of .NET required for your app
    commands:
      - echo "Installing dependencies"
      - dotnet restore

  build:
    commands:
      - echo "Building the application"
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Packaging the build artifacts"
      - dotnet publish --configuration Release --output ./output
      - echo "Build and package completed"

artifacts:
  files:
    - output//* # Include all files from the publish output folder
  discard-paths: no # Retain folder structure in the S3 bucket
